### ISSUE TITLE
Make it easy to get to this repo from the docs site

### ISSUE THREAD

**Issue by mattgallagher92** [RonaldSchlenker/Vide.docs#2]
It took me longer than I'd care to admit to find this repo from starting from https://vide-dev.io/ :sweat_smile: this is because https://vide-dev.io/ links to https://github.com/RonaldSchlenker/Vide, and neither https://vide-dev.io/ nor https://github.com/RonaldSchlenker/Vide links to this repo.

**Comment by SchlenkR** [comment]
I'm sorry for the inconvenience. I linked this repo in the related commits for making it more discoverable (or: discoverable at all). Feel free to DM / reach out in the future when facing any inconvenience.

**Comment by SchlenkR** [comment]
In general I'm not sure if such a docu is useful and helpful for a project like Vide, which is quite simple and small from a user perspective - or if a simple and to the point README.md wouldn't be sufficient or even better. Do you have an opinion on this @mattgallagher92?

**Comment by mattgallagher92** [comment]
No problem! Thanks for putting the docs together, it's an area that lets some OSS projects down, but I can see that Vide is already off to a great start 😄

The additional links you've put in are perfect 👍 

I prefer the separate docs site. Each page is simple and to the point, but I wouldn't want to have all that info in one README, nor would I want any to lose any of it to make the README smaller - it's all valuable. My vote is to keep things the way you have them.

Thanks!

**Comment by SchlenkR** [comment]
Thank you for the useful input and sharing thoughts and experience. I hope to being able finalizing a v1 release with complete documents until August.
